### ISSUE TITLE
Repository is blank for analyzethis application

### ISSUE THREAD

**Issue by mwaseem75** [diashenrique/zpm-explorer#11]
Hi,

In the application list the Repository is blank against analyze application. May be it requires some filtration.

Thanks

**Comment by diashenrique** [comment]
Hi, 

The ZPM Explorer gets the data using this endpoint: https://pm.community.intersystems.com/packages/-/all

If you take a look at the data response, you can see that Analyzethis repository field is empty.

![Screen Shot 2021-07-13 at 11 53 16](https://user-images.githubusercontent.com/4448425/125474197-dba48014-e3bc-4238-9872-09e44c02827b.png)
