### ISSUE TITLE
Error during installation in a dependent module ssl-client

### ISSUE THREAD

**Issue by SergeyMi37** [diashenrique/zpm-explorer#5]
docker-compose build
...
[sslclient]     Reload START
Skipping preload - directory does not exist.
Load started on 06/10/2021 17:58:18

ERROR #5012: File '/usr/irissys/mgr/.modules/IRISAPP/sslclient/1.0.3/src/community/utils/SSLClient.xml' does not exist
Detected 1 errors during load.

ERROR #5012: File '/usr/irissys/mgr/.modules/IRISAPP/sslclient/1.0.3/src/community/utils/SSLClient.xml' does not exist
[sslclient]     Reload FAILURE - ERROR #5012: File '/usr/irissys/mgr/.modules/IRISAPP/sslclient/1.0.3/src/community/utils/SSLClient.xml' does not exist
ERROR #5012: File '/usr/irissys/mgr/.modules/IRISAPP/sslclient/1.0.3/src/community/utils/SSLClient.xml' does not existThe command '/bin/sh -c iris start IRIS      && iris session IRIS < iris.script     && iris stop IRIS quietly' returned a non-zero code: 1
ERROR: Service 'iris' failed to build : Build failed

**Comment by SergeyMi37** [comment]
uname -a
Linux HP-MSW 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by diashenrique** [comment]
We'll check what's going on with the SSLClient. Thanks for sharing

**Comment by diashenrique** [comment]
fixed on issue from intersystems-community/ssl-client#2
